name: Build
on:
  push:
    paths-ignore:
      - '.editorconfig'
      - 'IMDB Parser.sln.DotSettings'
      - 'Readme.md'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install GPR Tool
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
        #run: dotnet tool install gpr --tool-path ~/tools
        run: dotnet tool install gpr --tool-path tools

      - name: Set API Key for GitHub Package Registry
        #run: ~/tools/gpr setApiKey ${{ secrets.GITHUB_TOKEN }}
        run: tools/gpr setApiKey ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: 3.1.100

      - name: Build
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test ImdbParser.Tests --configuration Release --no-build /p:CollectCoverage=true /p:ExcludeByAttribute=GeneratedCodeAttribute /p:CoverletOutputFormat=lcov

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./ImdbParser.Tests/coverage.info"
#/p:Threshold=100
# dotnet test ImdbParser.IntegrationTests --configuration Release --no-build /p:CollectCoverage=true /p:Exclude=[Core]*%2C[TestsCore]* /p:ExcludeByAttribute=GeneratedCodeAttribute /p:MergeWith='../ImdbParser.Tests/coverage.json'